version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: datenbankprojekt
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
    volumes:
      - data_db:/var/lib/mysql

volumes:
  data_db: